name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle


    - name: Download gradle-wrapper.jar
      run: |
        PROPERTIES_FILE=gradle/wrapper/gradle-wrapper.properties
        DIST_URL=$(grep "^distributionUrl=" "$PROPERTIES_FILE" | cut -d'=' -f2-)
        WRAPPER_JAR_URL=${DIST_URL/bin.zip/wrapper.jar}
        mkdir -p gradle/wrapper
        curl -L -o gradle/wrapper/gradle-wrapper.jar "$WRAPPER_JAR_URL"

    - name: Verify gradle-wrapper.jar
      run: ls -l gradle/wrapper

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Build Release APK
      run: ./gradlew assembleRelease --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: VDLink-release
        path: app/build/outputs/apk/release/app-release-unsigned.apk
