name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle


    - name: Setup Gradle and Generate Wrapper
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.5
        arguments: wrapper

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Decode Keystore and Build Release APK
      env:
        SIGNING_KEY_STORE_BASE64: ${{ secrets.SIGNING_KEY_STORE_BASE64 }}
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      run: |
        if [ -n "$SIGNING_KEY_STORE_BASE64" ]; then
          echo $SIGNING_KEY_STORE_BASE64 | base64 --decode > app/keystore.jks
          ./gradlew assembleRelease --stacktrace
        else
          echo "Signing secrets not found, building unsigned APK."
          ./gradlew assembleRelease --stacktrace
        fi

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: VDLink-release
        path: app/build/outputs/apk/release/app-release.apk
